import "../styles/About.css";
import Comp_Lab from "../assets/Comp_Lab.jpg"
import Library from "../assets/Library.jpg"
import Class from "../assets/Class.jpg"
import Sports from "../assets/Sports.jpg"

function About() {
  return (
    <div className="about-container">
      <h1>About ODRA Institute of Technology</h1>

      <div className="about-section">
        <h2>History</h2>
        <p>
          ODRA Institute of Technology was established with a vision to provide high-quality technical and
          professional education that empowers students to excel in a rapidly evolving world. Since its inception, the
          institute has remained committed to academic excellence, innovation, and holistic development.
        </p>
        <p>
          Over the years, the college has steadily grown into a reputed center of learning, equipped with modern
          infrastructure, experienced faculty, and industry-oriented programs. It has consistently nurtured talented
          individuals who have gone on to contribute significantly to various sectors such as engineering, technology,
          research, and entrepreneurship.
        </p>
        <p>
          With a strong foundation built on values, discipline, and continuous improvement, ODRA Institute of
          Technology continues to shape future professionals and leaders, preparing them to meet global challenges
          with confidence and competence.
        </p>
      </div>

      <div className="about-section">
        <h2>Departments</h2>
        <div className="card-container">
          <div className="card cse"><h2>Computer Science Engineering</h2></div>
          <div className="card mech"><h2>Mechanical Engineering</h2></div>
          <div className="card elec"><h2>Electrical Engineering</h2></div>
          <div className="card civil"><h2>Civil Engineering</h2></div>
        </div>
      </div>

      <div className="about-section">
        <h2>Faculty</h2>
        <div className="card-container">
          <div className="card faculty-1">
            <h3>Experienced Professors</h3>
            <p>Highly qualified and industry-experienced faculty members.</p>
          </div>
          <div className="card faculty-2">
            <h3>Supportive Mentors</h3>
            <p>Guiding students in academics, research, and career growth.</p>
          </div>
        </div>
      </div>

      <div className="about-section">
        <h1>Infrastructure</h1>
        <div className="Box">
          <div className="Box-Line-1">
            <li>Advanced Computer Labs</li>
            <img src={Comp_Lab} alt="Comp Lab"/>
            <li>Central Library with Digital Resources</li>
            <img src={Library} alt="Comp Lab"/>
          </div>
          <div className="Box-Line-2">
            <li>Sports & Recreation Facilities</li>
            <img src={Sports} alt="Comp Lab"/>
            <li>Modern Classrooms & Auditorium</li>
            <img src={Class} alt="Comp Lab"/>
          </div>
        </div>
      </div>

    </div>
  );
}
//All the information was generated by AI and none of it is real some ideas were taken from AI and implemented according to my likings
export default About;